name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    strategy:
      matrix:
        cabal: ['3.2']
        ghc: ['8.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build
      - run: cabal v2-test
      - run: cabal v2-haddock
      - run: cabal v2-sdist
